### ISSUE TITLE
能不能把代码结构讲一讲，我想学T_T

### ISSUE THREAD

**Issue by zltl** [AntiMoron/MDZZ-Calculator#1]
好短呀．

**Comment by zltl** [comment]
No bother. I have read it my self.

Thanks all the same.

**Comment by AM-young-fun** [comment]
噗。。。我才看到。。。

**Comment by AM-young-fun** [comment]
我也是现学现卖、

有个地方的特殊处理还没做。

**Comment by zltl** [comment]
还没写完？(´･_･`)

**Comment by AM-young-fun** [comment]
结合性问题没处理、 应该是树展开重新生成的、

比如例子里给的12/6/2、算出来4.、
